export type Habit = {id:string;name:string;type:'build'|'break';cue:string;behavior:string;reward:string;barrier:string;time:string;firstStep:string;createdAt:string};
export type Entry = {id:string;habitId:string;date:string;status:'completed'|'missed';phone:'away'|'nearby'|'unknown';strategy:string;trigger:string;hour:number;minutes:number;note:string};
export type Message = {role:'user'|'assistant';content:string};
export function dayKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function shiftDay(n:number){const d=new Date();d.setDate(d.getDate()+n);return dayKey(d);}
export const strategies=['5-minute start','Phone away','Habit stacking','Small reward','Environment reset','No strategy'];
export function tinyStep(name:string,type:Habit['type']='build'){const n=name.toLowerCase();if(type==='break'&&/drink|soda|energy drink|caffeine/.test(n))return 'Move the drink out of reach and choose a glass of water instead.';if(/homework|study|precalc|procrastin|assignment/.test(n))return 'Open your assignment and read the first question.';if(/water|drink/.test(n))return 'Fill a glass and take one sip.';if(/read|book/.test(n))return 'Open your book and read one page.';if(/exercise|walk|run|workout/.test(n))return 'Put on your shoes and move for two minutes.';if(/phone|scroll|social|youtube/.test(n))return 'Put your phone out of reach and take one slow breath.';if(/sleep|bed/.test(n))return 'Dim the lights and put your phone away.';return `Set up what you need for ${name.toLowerCase()} and try just two minutes.`;}
export function makePlan(h:Habit){const phone=/phone|tiktok|youtube|social|game/i.test(h.behavior);const hard=/overwhelm|difficult|start|wrong/i.test(h.barrier);return h.type==='build' ? [
 {rule:'Make it obvious',action:`After ${h.cue.toLowerCase()}, leave a visible reminder for ${h.name.toLowerCase()}.`,why:'Give your next action a clear cue.',icon:'eye'},
 {rule:'Make it attractive',action:`Pair your first step with ${h.reward.toLowerCase()}.`,why:'Give yourself a reason to look forward to starting.',icon:'heart'},
 {rule:'Make it easy',action:h.firstStep,why:hard?'Lower the pressure. Starting is enough.':'Make the smallest version count.',icon:'feather'},
 {rule:'Make it satisfying',action:'Check in after your session and notice one thing that felt better.',why:'Acknowledge the effort, even when it is small.',icon:'sparkles'}
 ] : [
 {rule:'Make it invisible',action:phone?`Before ${h.time}, put your phone out of reach and close entertainment tabs.`:`Remove the reminder of ${h.behavior.toLowerCase()} before ${h.cue.toLowerCase()}.`,why:'Change the cue before it becomes an automatic choice.',icon:'eye'},
 {rule:'Make it unattractive',action:`Write down what ${h.behavior.toLowerCase()} costs you, then compare it with the ${h.reward.toLowerCase()} you want.`,why:'Name the trade-off without judging yourself.',icon:'heart'},
 {rule:'Make it difficult',action:phone?'Log out of your distraction apps. Keep your phone in another room.':`Add a pause: move what you need for ${h.behavior.toLowerCase()} out of easy reach.`,why:'Add friction to the old behavior.',icon:'shield'},
 {rule:'Make it unsatisfying',action:'Record how the choice actually felt. Use that reflection to plan your next attempt.',why:'Use honest feedback, never punishment.',icon:'sparkles'}
 ];}
export function bestStrategy(logs:Entry[]){const groups=strategies.filter(s=>s!=='No strategy').map(name=>{const a=logs.filter(l=>l.strategy===name);return {name,n:a.length,wins:a.filter(l=>l.status==='completed').length,score:(a.filter(l=>l.status==='completed').length+1)/(a.length+2)};}).filter(g=>g.n>=3).sort((a,b)=>b.score-a.score||b.n-a.n);return groups[0]??null;}
export function phoneInsight(logs:Entry[]){const away=logs.filter(l=>l.phone==='away'),near=logs.filter(l=>l.phone==='nearby');const rate=(a:Entry[])=>a.length?Math.round(100*a.filter(l=>l.status==='completed').length/a.length):0;return {awayN:away.length,nearN:near.length,awayRate:rate(away),nearRate:rate(near),ready:away.length>=5&&near.length>=5};}
export function groupRates(logs:Entry[],kind:string){const labels=kind==='day'?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:kind==='time'?['Before noon','12–5 PM','5–8 PM','After 8 PM']:kind==='strategy'?strategies:[...new Set(logs.map(l=>l.trigger))].slice(0,6);return labels.map((label,i)=>{const a=logs.filter(l=>kind==='day'?((new Date(l.date+'T12:00:00').getDay()+6)%7)===i:kind==='time'?(l.hour<12?0:l.hour<17?1:l.hour<20?2:3)===i:kind==='strategy'?l.strategy===label:l.trigger===label);const successes=a.filter(l=>l.status==='completed').length;return {label,n:a.length,successes,rate:a.length?Math.round(100*successes/a.length):0};});}
export function earnedXP(logs:Entry[],habits:Habit[]){return logs.reduce((total,l)=>{if(l.status!=='completed')return total;const prev=new Date(l.date+'T12:00:00');prev.setDate(prev.getDate()-1);const recovery=logs.some(x=>x.habitId===l.habitId&&x.date===dayKey(prev)&&x.status==='missed');return total+10+(l.minutes>0&&habits.find(h=>h.id===l.habitId)?.type==='break'?15:0)+(l.strategy&&l.strategy!=='No strategy'?5:0)+(recovery?10:0);},0);}
export function coachReply(h:Habit|undefined,logs:Entry[],text:string){if(!h)return 'Let’s give your goal a little structure. Add a habit first, and I’ll help you find its cue, a tiny first step, and a strategy to try.';const best=bestStrategy(logs.filter(l=>l.habitId===h.id));const opening=/miss|fail|again|yesterday/i.test(text)?'One missed day does not erase your progress. Your next choice is a fresh start.':/tired|exhaust/i.test(text)?'Let’s lower the effort today. A smaller version still counts.':/overwhelm|hard|difficult|precalc|avoid|start/i.test(text)?'You do not need to finish everything right now. Let’s make starting feel manageable.':`Let’s work on ${h.name.toLowerCase()} with one small experiment.`;const step=/precalc/i.test(text)?'Open your precalculus assignment and read problem one.':/biology/i.test(text)?'Open your biology assignment and read question one.':h.firstStep;return `${opening}\n\nYour usual cue is “${h.cue}”, and the obstacle you identified is “${h.barrier}”.\n\n${/phone|youtube|social|tiktok/i.test(h.behavior)?'Put your phone out of reach. ':''}${step}\n\n${best?`${best.name} has worked in ${best.wins} of your ${best.n} logged attempts. Try it again; this is a pattern, not proof of cause.`:'We are still learning what works for you. Try a five-minute start, then log how it went.'}\n\nReady for five minutes? You can stop when the timer ends.`;}
export function demoData(){const habits:Habit[]=[{id:'demo-water',name:'Drink more water',type:'build',cue:'After breakfast',behavior:'Forget to drink',reward:'Feeling refreshed',barrier:'I forget',time:'8:00 AM',firstStep:'Fill a glass and take one sip.',createdAt:shiftDay(-30)},{id:'demo-study',name:'Study for 20 minutes',type:'build',cue:'After dinner',behavior:'Scroll on my phone',reward:'A favorite playlist',barrier:'It feels overwhelming',time:'7:00 PM',firstStep:'Open your notes and read one paragraph.',createdAt:shiftDay(-30)},{id:'demo-focus',name:'Stop procrastinating',type:'break',cue:'A difficult assignment',behavior:'Open YouTube on my phone',reward:'Temporary relief from stress',barrier:"I don’t know where to start",time:'7:00 PM',firstStep:'Open your assignment and read the first question.',createdAt:shiftDay(-30)}];const logs:Entry[]=[];for(let i=28;i>=1;i--){habits.forEach((h,j)=>{const away=i%2===0;const success=j===0?i%7!==0:j===1?i%4!==0:away?i%12!==0:i%3===0;logs.push({id:`demo-${i}-${j}`,habitId:h.id,date:shiftDay(-i),status:success?'completed':'missed',phone:away?'away':'nearby',strategy:j===0?'Habit stacking':away?'5-minute start':'Environment reset',trigger:h.cue,hour:away?19:21,minutes:success?5:0,note:''});});}logs.push({id:'demo-today',habitId:habits[0].id,date:dayKey(),status:'completed',phone:'unknown',strategy:'Habit stacking',trigger:habits[0].cue,hour:8,minutes:0,note:''});return {habits,logs};}
